// <auto-generated />
using System;
using FullText.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace FullText.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullText.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("DuoDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duo_date");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(\"title\", '')), 'A') ||\r\nsetweight(to_tsvector('english', coalesce(\"content\", '')), 'B') ||\r\nsetweight(to_tsvector('english', coalesce(\"excerpt\", '')), 'C')", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_blogs");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_blogs_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Domain-Driven Design (DDD) is a methodology for tackling complexity in software by\r\nfocusing on the core domain and domain logic. DDD encourages a rich domain model\r\nbuilt from entities, value objects, and aggregates that enforce invariants. Every\r\nserious DDD implementation revolves around an aggregate root that controls access\r\nto the objects within its consistency boundary.\r\n\r\nA central concept in Domain-Driven Design is the ubiquitous language — a shared\r\nvocabulary between developers and domain experts. DDD also introduces bounded\r\ncontexts, letting large domain models split into smaller, independently evolvable\r\npieces, each with its own domain language and its own DDD-driven design decisions.",
                            DuoDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "An introduction to DDD building blocks — entities, value objects, and aggregates.",
                            Title = "Domain-Driven Design: Modeling Complex Business Logic"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bounded contexts are one of the most practically useful ideas from Domain-Driven\r\nDesign. A bounded context defines an explicit boundary within which a particular\r\ndomain model applies, with its own ubiquitous language shared between developers\r\nand domain experts.\r\n\r\nApplying DDD without bounded contexts often leads to a single bloated model trying\r\nto represent every concern of the business at once. Splitting by bounded context\r\nkeeps each domain model focused, and lets teams evolve their piece of the system\r\nindependently under DDD principles.",
                            DuoDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Why splitting your domain model matters in Domain-Driven Design.",
                            Title = "Bounded Contexts and the Ubiquitous Language"
                        },
                        new
                        {
                            Id = 3,
                            Content = "An aggregate is a cluster of associated objects treated as a single unit for data\r\nchanges, with a designated aggregate root as the only entry point. This pattern,\r\nborrowed from DDD, ensures invariants are enforced consistently rather than scattered\r\nacross the codebase.\r\n\r\nDomain events allow an aggregate to signal that something meaningful happened,\r\nwithout coupling directly to whoever reacts to it. This keeps the domain model\r\nexpressive while staying decoupled from infrastructure concerns.",
                            DuoDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "How aggregates enforce consistency and emit meaningful domain events.",
                            Title = "Aggregates and Domain Events Explained"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Clean Architecture organizes an application into concentric layers, with core\r\nbusiness rules at the center and infrastructure concerns pushed to the outer\r\nedges. Dependencies always point inward, so the domain layer never depends on\r\ndatabases, frameworks, or UI technology.\r\n\r\nMany teams pair Clean Architecture with ideas from DDD to shape the innermost\r\nlayer, though Clean Architecture itself is a broader structural pattern that\r\napplies even to simpler, non-domain-heavy applications.",
                            DuoDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Structuring .NET applications around dependency inversion and clear layers.",
                            Title = "Clean Architecture and Layered .NET Systems"
                        },
                        new
                        {
                            Id = 5,
                            Content = "A modular monolith organizes a single deployable application into well-isolated\r\nmodules, each owning its own data and business logic, communicating only through\r\nexplicit public contracts. This modular monolith approach gives teams many of the\r\nboundary benefits of microservices without the distributed-systems complexity of\r\nnetwork calls and deployment orchestration.\r\n\r\nEach module in a modular monolith can apply its own internal architecture, and\r\nmodular monolith systems often enforce boundaries through internal visibility\r\nmodifiers or dedicated architecture tests.",
                            DuoDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "How to structure a monolith into independent modules without microservices overhead.",
                            Title = "Modular Monolith: The Middle Ground Between Monolith and Microservices"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Enforcing module boundaries in a modular monolith usually relies on internal\r\nvisibility modifiers, architecture tests, or build-time analyzers that fail the\r\nbuild if a module reaches into another module's internals.\r\n\r\nA well-structured modular monolith treats each module almost like a service,\r\nexposing a small public surface area while keeping implementation details private\r\nto that module alone.",
                            DuoDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Techniques for keeping modules independent inside a single deployable.",
                            Title = "Enforcing Module Boundaries in a Modular Monolith"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Many teams jump to microservices before their monolith actually needs the split.\r\nA modular monolith is often a safer intermediate step, letting a team validate\r\nmodule boundaries before paying the operational cost of distributed deployment.\r\n\r\nIf you find your modules rarely change independently, microservices may add\r\noverhead without real benefit — staying a monolith, modular or otherwise, can be\r\nthe pragmatic choice.",
                            DuoDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Evaluating whether microservices are the right next step for a growing system.",
                            Title = "From Monolith to Microservices: When to Make the Jump"
                        },
                        new
                        {
                            Id = 8,
                            Content = ".NET applications can be deployed as self-contained executables, framework-dependent\r\nbinaries, or containers orchestrated by Kubernetes. The right strategy depends on\r\nyour team's operational maturity and infrastructure.\r\n\r\nWhether you deploy a modular monolith or a set of independent services, deployment\r\npipeline reliability matters more than the chosen architecture style.",
                            DuoDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Comparing deployment approaches from single binaries to container orchestration.",
                            Title = "Deployment Strategies for .NET Applications"
                        },
                        new
                        {
                            Id = 9,
                            Content = "xUnit is one of the most popular testing frameworks for .NET, favored for its\r\nextensibility and clean attribute-based syntax. A basic xUnit test class requires no\r\nbase class — tests are public methods decorated with [Fact], or [Theory] combined\r\nwith [InlineData] for parameterized cases.\r\n\r\nxUnit creates a new instance of the test class for every test method, isolating\r\nstate between tests. Assertions in xUnit are handled through the static Assert\r\nclass, with methods like Assert.Equal, Assert.Throws, and Assert.Collection.",
                            DuoDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "A beginner's guide to structuring and running unit tests with xUnit in .NET.",
                            Title = "Getting Started with xUnit: Writing Your First .NET Tests"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Test-Driven Development with xUnit follows the red-green-refactor loop: write a\r\nfailing xUnit test, write the minimal code to pass it, then refactor. xUnit's fast\r\ntest discovery and parallel execution make this loop quick enough to sustain\r\nthroughout a working day.\r\n\r\nMocking libraries like Moq pair naturally with xUnit's constructor-based fixture\r\npattern, letting you inject fake dependencies into your xUnit test classes without\r\ntouching real infrastructure.",
                            DuoDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Practical TDD techniques using xUnit, Moq, and dependency injection.",
                            Title = "Test-Driven Development with xUnit and Mocking"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Integration tests validate that your application works correctly against real\r\ninfrastructure — a real database, a real message broker — rather than mocks.\r\nTestcontainers makes this practical by spinning up disposable Docker containers\r\nfor the duration of a test run.\r\n\r\nThese integration tests are commonly written using xUnit as the runner, combined\r\nwith collection fixtures to share an expensive container across multiple test\r\nclasses rather than starting one per test.",
                            DuoDate = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Spinning up real dependencies in tests using Testcontainers.",
                            Title = "Integration Testing in .NET with Test Containers"
                        },
                        new
                        {
                            Id = 12,
                            Content = "As a test suite grows, maintainability becomes as important as coverage. Favor\r\nclear naming, avoid shared mutable state between tests, and keep individual tests\r\nfocused on a single behavior rather than asserting on many unrelated outcomes.\r\n\r\nWhatever framework you use — xUnit, NUnit, or MSTest — the same principles of test\r\nisolation and clarity apply equally well.",
                            DuoDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "General principles for keeping a growing test suite fast and reliable.",
                            Title = "Writing Maintainable Test Suites"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Command Query Responsibility Segregation (CQRS) is an architectural pattern that\r\nseparates the write model (commands) from the read model (queries). Under CQRS,\r\ncommands mutate state and return no data, while queries return data and never\r\nmutate state.\r\n\r\nTeams adopting CQRS often introduce a mediator to dispatch commands and queries to\r\ntheir respective handlers, keeping the API layer thin. CQRS pairs naturally with\r\nevent sourcing, though the two patterns are independent.",
                            DuoDate = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Why splitting command and query responsibilities can simplify complex systems.",
                            Title = "CQRS: Separating Reads from Writes"
                        },
                        new
                        {
                            Id = 14,
                            Content = "When Domain-Driven Design and CQRS are combined, the domain model becomes the\r\nsource of truth for command validation, while a separate read model serves queries.\r\nAggregates emit domain events as the output of every CQRS command, which an event\r\nstore persists as the authoritative log.\r\n\r\nCQRS command handlers load an aggregate by replaying its events, apply the requested\r\nbehavior, and append new events back to the store — query handlers subscribe to the\r\nsame stream to build read-optimized projections.",
                            DuoDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "A practical walkthrough of applying Domain-Driven Design and CQRS together.",
                            Title = "Combining DDD and CQRS in an Event-Sourced System"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Reporting dashboards typically need data shaped very differently from your\r\ntransactional write model. Building a dedicated, denormalized read model — an\r\napproach closely related to CQRS — lets queries stay fast without complicating the\r\nwrite side with reporting concerns.\r\n\r\nThis read model can be refreshed on a schedule or updated incrementally as events\r\narrive, depending on how fresh the reporting data needs to be.",
                            DuoDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Designing denormalized read models optimized for fast queries.",
                            Title = "Building Read Models for Reporting Dashboards"
                        },
                        new
                        {
                            Id = 16,
                            Content = "Scalable API design often involves pagination, caching, rate limiting, and clear\r\nversioning strategies. Some teams also split their API surface following CQRS-like\r\nprinciples, exposing distinct endpoints for commands versus queries even without a\r\nfull CQRS implementation underneath.\r\n\r\nRegardless of the pattern chosen, consistent error handling and predictable\r\nresponse shapes matter more to API consumers than the internal architecture.",
                            DuoDate = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Common patterns for building APIs that scale gracefully under load.",
                            Title = "API Design Patterns for Scalable Systems"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Kubernetes is a container orchestration platform that schedules, scales, and heals\r\nworkloads across a cluster of machines. The smallest deployable unit in Kubernetes\r\nis the Pod, typically wrapped by a Kubernetes Deployment that manages rolling\r\nupdates and replica counts.\r\n\r\nA Kubernetes Service provides a stable network identity for a set of Pods, while\r\nKubernetes ConfigMaps and Secrets externalize configuration so container images\r\nstay environment-agnostic across every Kubernetes cluster you run.",
                            DuoDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "A tour of core Kubernetes objects and how they fit together.",
                            Title = "Kubernetes Fundamentals: Pods, Deployments, and Services"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Horizontal Pod Autoscaling lets Kubernetes add or remove Pod replicas automatically\r\nbased on observed CPU, memory, or custom metrics. This keeps a Kubernetes workload\r\nresponsive during traffic spikes without manual intervention.\r\n\r\nCombined with Cluster Autoscaler, which adds nodes to the underlying Kubernetes\r\ncluster when Pods can't be scheduled, teams can scale both application and\r\ninfrastructure layers together.",
                            DuoDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "How Kubernetes automatically scales workloads based on load.",
                            Title = "Scaling Applications with Horizontal Pod Autoscaling"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Kubernetes is the dominant orchestrator, but it isn't the only option. Docker Swarm\r\noffers a much simpler operational model for small teams, and managed platform\r\nservices like AWS ECS or Azure Container Apps abstract away most of what Kubernetes\r\nexposes directly.\r\n\r\nThe right choice depends on team size and operational appetite — Kubernetes gives\r\nthe most flexibility but demands the most expertise to run well in production.",
                            DuoDate = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Comparing simpler alternatives for teams that don't need a full cluster.",
                            Title = "Container Orchestration Options Beyond Kubernetes"
                        },
                        new
                        {
                            Id = 20,
                            Content = "A solid CI/CD pipeline builds, tests, and packages a .NET application on every\r\ncommit, then promotes the artifact through staging and production environments\r\nwith minimal manual steps.\r\n\r\nThe final deployment target might be a set of Kubernetes manifests, a container\r\nregistry push, or a simple app-service deployment — the pipeline discipline matters\r\nmore than which target it eventually deploys to.",
                            DuoDate = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Building automated build, test, and release pipelines for .NET projects.",
                            Title = "CI/CD Pipelines for .NET Applications"
                        },
                        new
                        {
                            Id = 21,
                            Content = "GraphQL is a query language for APIs that lets clients specify exactly which fields\r\nthey need, avoiding the over-fetching and under-fetching common with fixed REST\r\nendpoints. A single GraphQL endpoint typically replaces dozens of REST routes.\r\n\r\nEvery GraphQL API is described by a strongly typed schema, and a GraphQL resolver\r\nis responsible for fetching the data behind each field, whether that means calling\r\na database, a cache, or another GraphQL service entirely.",
                            DuoDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Why GraphQL lets clients request exactly the data they need.",
                            Title = "GraphQL vs REST: Designing Flexible APIs"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Hot Chocolate is a popular GraphQL server for .NET that supports queries, mutations,\r\nand subscriptions out of the box. GraphQL subscriptions push updates to connected\r\nclients over WebSockets whenever the underlying data changes.\r\n\r\nSetting up a GraphQL subscription usually means wiring an in-memory or Redis-backed\r\npub/sub provider so multiple server instances can broadcast the same event to every\r\nsubscribed client.",
                            DuoDate = new DateTime(2024, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Adding real-time updates to a .NET GraphQL API.",
                            Title = "Implementing GraphQL Subscriptions in .NET with Hot Chocolate"
                        },
                        new
                        {
                            Id = 23,
                            Content = "An API gateway sits in front of a set of microservices, handling authentication,\r\nrate limiting, and request routing in one place so individual services don't\r\nduplicate that logic. Some gateways expose a GraphQL layer that stitches together\r\nresponses from several backend services into a single query.\r\n\r\nChoosing between a REST-style gateway and a GraphQL-based one usually comes down to\r\nhow varied your client applications' data needs are.",
                            DuoDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Centralizing cross-cutting concerns in front of a microservices architecture.",
                            Title = "API Gateway Patterns for Microservices"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Public APIs need rate limiting to protect backend resources from abusive or\r\naccidental overuse. Common approaches include fixed windows, sliding windows, and\r\ntoken buckets, each with different trade-offs around burst tolerance.\r\n\r\nThese strategies apply whether the API surface is REST, GraphQL, or something else\r\nentirely — the limiter sits in front of the request pipeline regardless of the\r\nunderlying query style.",
                            DuoDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Protecting backend services from abuse and traffic spikes.",
                            Title = "Rate Limiting Strategies for Public APIs"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Event-driven architecture decouples services by having them publish events to a\r\nbroker rather than calling each other directly. Producers in an event-driven system\r\ndon't need to know which consumers, if any, will react to an event.\r\n\r\nA message broker like RabbitMQ or Kafka sits at the center of most event-driven\r\narchitectures, durably storing and routing events so consumers can process them\r\nindependently, at their own pace, without coupling to producer availability.",
                            DuoDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Decoupling services by communicating through events instead of direct calls.",
                            Title = "Event-Driven Architecture with Message Brokers"
                        },
                        new
                        {
                            Id = 26,
                            Content = "The outbox pattern solves a classic event-driven problem: how to atomically update\r\nyour database and publish an event without a distributed transaction. A service\r\nwrites the event to an outbox table in the same local transaction as its data\r\nchange, then a separate relay process publishes it to the broker.\r\n\r\nThis keeps event-driven systems consistent even if the process crashes between the\r\ndatabase write and the network call to the broker.",
                            DuoDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Guaranteeing events are published even when a service crashes mid-transaction.",
                            Title = "Implementing the Outbox Pattern for Reliable Messaging"
                        },
                        new
                        {
                            Id = 27,
                            Content = "RabbitMQ is a traditional message broker built around queues and flexible routing,\r\nwhile Kafka is a distributed log optimized for high-throughput streaming and replay.\r\nBoth can anchor an event-driven system, but they suit different access patterns.\r\n\r\nKafka's ability to replay a full event history makes it attractive for analytics\r\nand event sourcing, while RabbitMQ's routing flexibility often fits simpler\r\ntask-queue style workloads better.",
                            DuoDate = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Comparing two popular message brokers for different workload shapes.",
                            Title = "Choosing Between RabbitMQ and Kafka"
                        },
                        new
                        {
                            Id = 28,
                            Content = "An idempotent API endpoint produces the same result no matter how many times an\r\nidentical request is retried, which matters enormously whenever clients or\r\nnetworks might duplicate a call. Idempotency keys let a server recognize and\r\nsafely ignore a repeated request.\r\n\r\nThis matters just as much for HTTP APIs as it does for event-driven consumers,\r\nsince message brokers commonly redeliver events at least once.",
                            DuoDate = new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Making sure repeated requests don't cause duplicate side effects.",
                            Title = "Designing Idempotent APIs"
                        },
                        new
                        {
                            Id = 29,
                            Content = "Redis is an in-memory data store commonly used as a caching layer in front of a\r\nslower primary database. Caching frequently read, rarely changed data in Redis can\r\nturn expensive queries into sub-millisecond lookups.\r\n\r\nCommon Redis caching strategies include cache-aside, where the application checks\r\nthe cache before falling back to the database, and write-through caching, where\r\nevery write updates the cache and the database together.",
                            DuoDate = new DateTime(2024, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Speeding up .NET applications with an in-memory cache layer.",
                            Title = "Caching Strategies with Redis in .NET"
                        },
                        new
                        {
                            Id = 30,
                            Content = "Cache invalidation is famously one of the two hardest problems in computer science.\r\nA cache that never expires eventually serves stale data, while one that expires too\r\naggressively loses most of its performance benefit.\r\n\r\nTime-based expiry, explicit invalidation on write, and event-driven cache busting\r\nare the three most common approaches, each trading off simplicity against\r\nfreshness guarantees.",
                            DuoDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Keeping cached data correct as the underlying data changes.",
                            Title = "Cache Invalidation Patterns: The Two Hard Problems"
                        },
                        new
                        {
                            Id = 31,
                            Content = "API latency budgets are usually dominated by database round trips and downstream\r\nservice calls, not application logic itself. Introducing a distributed cache in\r\nfront of the slowest calls is often the single highest-leverage latency fix\r\navailable to a team.\r\n\r\nBeyond caching, connection pooling, response compression, and reducing serialization\r\noverhead all contribute meaningfully to a faster API.",
                            DuoDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "A latency-focused look at where caching fits in a request path.",
                            Title = "Improving API Latency with Distributed Caching"
                        },
                        new
                        {
                            Id = 32,
                            Content = "PostgreSQL indexes speed up lookups at the cost of extra storage and slower writes,\r\nso indexing every column is rarely the right call. B-tree indexes cover most\r\nequality and range queries, while GIN indexes suit full-text search and array\r\ncontainment lookups.\r\n\r\nFor read-heavy tables, a well-chosen index often beats adding a caching layer\r\nentirely, since it fixes the underlying query cost rather than papering over it.",
                            DuoDate = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Choosing the right indexes to keep queries fast as tables grow.",
                            Title = "Database Indexing Best Practices for PostgreSQL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
